GAMES = [
    {
        "id": "zelda_botw",
        "name": "The Legend of Zelda: Breath of the Wild",
        "genre": "aventura",
        "platform": "nintendo",
        "mode": "singleplayer",
        "difficulty": "media",
        "duration": "larga",
        "mood": "explorar",
        "image": "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80",
        "tags": ["mundo abierto", "fantasia", "exploracion"],
    },
    {
        "id": "stardew_valley",
        "name": "Stardew Valley",
        "genre": "simulacion",
        "platform": "pc",
        "mode": "ambos",
        "difficulty": "baja",
        "duration": "larga",
        "mood": "relajarse",
        "image": "https://images.unsplash.com/photo-1585504198199-20277593b94f?auto=format&fit=crop&w=900&q=80",
        "tags": ["granjas", "cooperativo", "gestion"],
    },
    {
        "id": "hades",
        "name": "Hades",
        "genre": "accion",
        "platform": "pc",
        "mode": "singleplayer",
        "difficulty": "alta",
        "duration": "media",
        "mood": "reto",
        "image": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80",
        "tags": ["roguelike", "mitologia", "combate"],
    },
    {
        "id": "minecraft",
        "name": "Minecraft",
        "genre": "sandbox",
        "platform": "pc",
        "mode": "ambos",
        "difficulty": "media",
        "duration": "larga",
        "mood": "crear",
        "image": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80",
        "tags": ["construccion", "supervivencia", "creatividad"],
    },
    {
        "id": "valorant",
        "name": "Valorant",
        "genre": "shooter",
        "platform": "pc",
        "mode": "multiplayer",
        "difficulty": "alta",
        "duration": "corta",
        "mood": "competir",
        "image": "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=900&q=80",
        "tags": ["tactico", "equipos", "online"],
    },
    {
        "id": "mario_kart_8",
        "name": "Mario Kart 8 Deluxe",
        "genre": "carreras",
        "platform": "nintendo",
        "mode": "ambos",
        "difficulty": "baja",
        "duration": "corta",
        "mood": "divertirse",
        "image": "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&w=900&q=80",
        "tags": ["fiesta", "familia", "competitivo"],
    },
    {
        "id": "elden_ring",
        "name": "Elden Ring",
        "genre": "rpg",
        "platform": "playstation",
        "mode": "singleplayer",
        "difficulty": "alta",
        "duration": "larga",
        "mood": "reto",
        "image": "https://images.unsplash.com/photo-1511882150382-421056c89033?auto=format&fit=crop&w=900&q=80",
        "tags": ["soulslike", "mundo abierto", "fantasia"],
    },
    {
        "id": "fifa_24",
        "name": "EA Sports FC 24",
        "genre": "deportes",
        "platform": "playstation",
        "mode": "ambos",
        "difficulty": "media",
        "duration": "corta",
        "mood": "competir",
        "image": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80",
        "tags": ["futbol", "online", "torneos"],
    },
    {
        "id": "portal_2",
        "name": "Portal 2",
        "genre": "puzzle",
        "platform": "pc",
        "mode": "ambos",
        "difficulty": "media",
        "duration": "media",
        "mood": "pensar",
        "image": "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=900&q=80",
        "tags": ["puzzles", "historia", "cooperativo"],
    },
    {
        "id": "animal_crossing",
        "name": "Animal Crossing: New Horizons",
        "genre": "simulacion",
        "platform": "nintendo",
        "mode": "singleplayer",
        "difficulty": "baja",
        "duration": "larga",
        "mood": "relajarse",
        "image": "https://images.unsplash.com/photo-1580327344181-c1163234e5a0?auto=format&fit=crop&w=900&q=80",
        "tags": ["vida social", "decoracion", "coleccion"],
    },
    {
        "id": "god_of_war",
        "name": "God of War Ragnarok",
        "genre": "accion",
        "platform": "playstation",
        "mode": "singleplayer",
        "difficulty": "media",
        "duration": "media",
        "mood": "historia",
        "image": "https://images.unsplash.com/photo-1560253023-3ec5d502959f?auto=format&fit=crop&w=900&q=80",
        "tags": ["narrativa", "mitologia", "combate"],
    },
    {
        "id": "among_us",
        "name": "Among Us",
        "genre": "social",
        "platform": "movil",
        "mode": "multiplayer",
        "difficulty": "baja",
        "duration": "corta",
        "mood": "divertirse",
        "image": "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?auto=format&fit=crop&w=900&q=80",
        "tags": ["deduccion", "amigos", "online"],
    },
]


OPTIONS = {
    "genres": ["accion", "aventura", "carreras", "deportes", "puzzle", "rpg", "sandbox", "shooter", "simulacion", "social"],
    "platforms": ["pc", "playstation", "nintendo", "movil"],
    "modes": ["singleplayer", "multiplayer", "ambos"],
    "difficulties": ["baja", "media", "alta"],
    "durations": ["corta", "media", "larga"],
    "moods": ["competir", "crear", "divertirse", "explorar", "historia", "pensar", "relajarse", "reto"],
}
