GAMES = [
    {
        "id": "zelda_botw",
        "name": "The Legend of Zelda: Breath of the Wild",
        "genre": "aventura",
        "platform": "nintendo",
        "mode": "singleplayer",
        "difficulty": "media",
        "duration": "larga",
        "mood": "explorar",
        "image": "/static/images/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
        "tags": ["mundo abierto", "fantasia", "exploracion"],
    },
    {
        "id": "stardew_valley",
        "name": "Stardew Valley",
        "genre": "simulacion",
        "platform": "pc",
        "mode": "ambos",
        "difficulty": "baja",
        "duration": "larga",
        "mood": "relajarse",
        "image": "/static/images/Stardew_Valley.png",
        "tags": ["granjas", "cooperativo", "gestion"],
    },
    {
        "id": "hades",
        "name": "Hades",
        "genre": "accion",
        "platform": "pc",
        "mode": "singleplayer",
        "difficulty": "alta",
        "duration": "media",
        "mood": "reto",
        "image": "/static/images/Hades.jpg",
        "tags": ["roguelike", "mitologia", "combate"],
    },
    {
        "id": "minecraft",
        "name": "Minecraft",
        "genre": "sandbox",
        "platform": "pc",
        "mode": "ambos",
        "difficulty": "media",
        "duration": "larga",
        "mood": "crear",
        "image": "/static/images/Minecraft.jpg",
        "tags": ["construccion", "supervivencia", "creatividad"],
    },
    {
        "id": "valorant",
        "name": "Valorant",
        "genre": "shooter",
        "platform": "pc",
        "mode": "multiplayer",
        "difficulty": "alta",
        "duration": "corta",
        "mood": "competir",
        "image": "/static/images/Valorant.jpg",
        "tags": ["tactico", "equipos", "online"],
    },
    {
        "id": "mario_kart_8",
        "name": "Mario Kart 8 Deluxe",
        "genre": "carreras",
        "platform": "nintendo",
        "mode": "ambos",
        "difficulty": "baja",
        "duration": "corta",
        "mood": "divertirse",
        "image": "/static/images/Mario_Kart_8_Deluxe.jpg",
        "tags": ["fiesta", "familia", "competitivo"],
    },
    {
        "id": "elden_ring",
        "name": "Elden Ring",
        "genre": "rpg",
        "platform": "playstation",
        "mode": "singleplayer",
        "difficulty": "alta",
        "duration": "larga",
        "mood": "reto",
        "image": "/static/images/Elden_Ring.jpg",
        "tags": ["soulslike", "mundo abierto", "fantasia"],
    },
    {
        "id": "fifa_24",
        "name": "EA Sports FC 24",
        "genre": "deportes",
        "platform": "playstation",
        "mode": "ambos",
        "difficulty": "media",
        "duration": "corta",
        "mood": "competir",
        "image": "/static/images/EA_Sports_FC_24.jpg",
        "tags": ["futbol", "online", "torneos"],
    },
    {
        "id": "portal_2",
        "name": "Portal 2",
        "genre": "puzzle",
        "platform": "pc",
        "mode": "ambos",
        "difficulty": "media",
        "duration": "media",
        "mood": "pensar",
        "image": "/static/images/Portal_2.jpg",
        "tags": ["puzzles", "historia", "cooperativo"],
    },
    {
        "id": "animal_crossing",
        "name": "Animal Crossing: New Horizons",
        "genre": "simulacion",
        "platform": "nintendo",
        "mode": "singleplayer",
        "difficulty": "baja",
        "duration": "larga",
        "mood": "relajarse",
        "image": "/static/images/Animal_Crossing_New_Horizons.jpg",
        "tags": ["vida social", "decoracion", "coleccion"],
    },
    {
        "id": "god_of_war",
        "name": "God of War Ragnarok",
        "genre": "accion",
        "platform": "playstation",
        "mode": "singleplayer",
        "difficulty": "media",
        "duration": "media",
        "mood": "historia",
        "image": "/static/images/God_of_War_Ragnarok.jpg",
        "tags": ["narrativa", "mitologia", "combate"],
    },
    {
        "id": "among_us",
        "name": "Among Us",
        "genre": "social",
        "platform": "movil",
        "mode": "multiplayer",
        "difficulty": "baja",
        "duration": "corta",
        "mood": "divertirse",
        "image": "/static/images/AmongUs.jpg",
        "tags": ["deduccion", "amigos", "online"],
    },
]


OPTIONS = {
    "genres": ["accion", "aventura", "carreras", "deportes", "puzzle", "rpg", "sandbox", "shooter", "simulacion", "social"],
    "platforms": ["pc", "playstation", "nintendo", "movil"],
    "modes": ["singleplayer", "multiplayer", "ambos"],
    "difficulties": ["baja", "media", "alta"],
    "durations": ["corta", "media", "larga"],
    "moods": ["competir", "crear", "divertirse", "explorar", "historia", "pensar", "relajarse", "reto"],
}
